/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import classes_principais.ListaUsuarios;
import classes_principais.Sistema;

/**
 *
 * @author kaua
 */
public class Home extends javax.swing.JFrame {
    /**
     * Creates new form Home
     */
    
    private ListaUsuarios usuarios;
    private Sistema banco;
    
    public Home(Sistema banco, ListaUsuarios usuarios) {
        this.banco = banco;
        if(usuarios != null){
            this.usuarios = usuarios;
        }
        
        //a ideia é, pelo menos teoricamente, chamar tudo do banco e inputar numa lista e daí efetuar as ações
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHome = new javax.swing.JLabel();
        btnAdvogadosCadastrados = new javax.swing.JButton();
        btnProcessosArquivados = new javax.swing.JButton();
        btnCadastrarAdvogado = new javax.swing.JButton();
        btnCadastrarProcesso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblHome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblHome.setText("HOME");

        btnAdvogadosCadastrados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAdvogadosCadastrados.setText("Advogados Cadastrados");
        btnAdvogadosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvogadosCadastradosActionPerformed(evt);
            }
        });

        btnProcessosArquivados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnProcessosArquivados.setText("Processos Arquivados");

        btnCadastrarAdvogado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadastrarAdvogado.setText("Cadastrar Advogado");
        btnCadastrarAdvogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAdvogadoActionPerformed(evt);
            }
        });

        btnCadastrarProcesso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadastrarProcesso.setText("Cadastrar Processo");
        btnCadastrarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProcessoActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("©2023 Copyright: Kauã Nogueira e Gabriel Silveira");

        btnSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addGap(170, 170, 170))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrarAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrarProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdvogadosCadastrados)
                        .addGap(18, 18, 18)
                        .addComponent(btnProcessosArquivados)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(lblHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblHome)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdvogadosCadastrados)
                    .addComponent(btnProcessosArquivados))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarAdvogado)
                    .addComponent(btnCadastrarProcesso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdvogadosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvogadosCadastradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdvogadosCadastradosActionPerformed

    private void btnCadastrarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProcessoActionPerformed
        new CadastroProcesso(banco, usuarios).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCadastrarProcessoActionPerformed

    private void btnCadastrarAdvogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAdvogadoActionPerformed
        new CadastroAdvogado(banco, usuarios).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCadastrarAdvogadoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        new Menu(usuarios, banco).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdvogadosCadastrados;
    private javax.swing.JButton btnCadastrarAdvogado;
    private javax.swing.JButton btnCadastrarProcesso;
    private javax.swing.JButton btnProcessosArquivados;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblHome;
    // End of variables declaration//GEN-END:variables
}
