/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import com.mycompany.entities.Advogado;
import javax.swing.UIManager;

/**
 *
 * @author kaua
 */
public class PerfilAdvogado extends javax.swing.JFrame {

    /**
     * Creates new form PerfilAdvogado
     * @param advogado
     */
    private final Advogado advogado;
    String nome_oficial;
    String codigo_oficial;
    
    public PerfilAdvogado(Advogado advogado){
        this.advogado = advogado;
        initComponents();
        String nome = this.advogado.getNome();
        nome_oficial = nome;
        String codigo = this.advogado.getCodigo();
        codigo_oficial = codigo;
        editavel(nome_oficial, codigo_oficial);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigo_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nome_txt = new javax.swing.JTextField();
        editar_btn = new javax.swing.JButton();
        salvar_btn = new javax.swing.JButton();
        adcionar_btn = new javax.swing.JButton();
        manter_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Perfil do Advogado");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Código");

        nome_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_txtActionPerformed(evt);
            }
        });

        editar_btn.setText("Editar");
        editar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_btnActionPerformed(evt);
            }
        });

        salvar_btn.setText("Salvar");
        salvar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_btnActionPerformed(evt);
            }
        });

        adcionar_btn.setText("Adcionar Processo");
        adcionar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adcionar_btnActionPerformed(evt);
            }
        });

        manter_btn.setText("Manter");
        manter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manter_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editar_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(manter_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salvar_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adcionar_btn)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(codigo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar_btn)
                    .addComponent(salvar_btn)
                    .addComponent(adcionar_btn)
                    .addComponent(manter_btn))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void editavel(String nome, String codigo){
       
        editar_btn.setVisible(true);
        adcionar_btn.setVisible(true);
        nome_txt.setEnabled(false);
        nome_txt.setDisabledTextColor(UIManager.getColor("TextField.foreground"));
        nome_txt.setCaretColor(UIManager.getColor("TextField.caretForeground"));
        codigo_txt.setEnabled(false);
        codigo_txt.setDisabledTextColor(UIManager.getColor("TextField.foreground"));
        codigo_txt.setCaretColor(UIManager.getColor("TextField.caretForeground"));
        salvar_btn.setVisible(false);
        manter_btn.setVisible(false);
        
        if(nome != null && codigo != null){
            nome_txt.setText(nome);
            codigo_txt.setText(codigo);
        }
       
    }
    private void editar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_btnActionPerformed
        //habilitar campos e botão salvar
        nome_txt.setEnabled(true);
        codigo_txt.setEnabled(true);
        salvar_btn.setVisible(true);
        manter_btn.setVisible(true);
        //desabilitar campo editar e adcionar processo
        adcionar_btn.setVisible(false);
        editar_btn.setVisible(false);
        
    }//GEN-LAST:event_editar_btnActionPerformed

    private void nome_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_txtActionPerformed

    }//GEN-LAST:event_nome_txtActionPerformed

    private void salvar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_btnActionPerformed
        String nome = nome_txt.getText();
        String codigo = codigo_txt.getText();
        this.advogado.setNome(nome);
        this.advogado.setCodigo(codigo);
        //se houver mais de um advogado, então remove o anterior e adciona o novo da lista (no futuro eu vou entender)
        new PerfilAdvogado(advogado).setVisible(true);
        dispose();
    }//GEN-LAST:event_salvar_btnActionPerformed

    private void manter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manter_btnActionPerformed
        editavel(nome_oficial, codigo_oficial);
    }//GEN-LAST:event_manter_btnActionPerformed

    private void adcionar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adcionar_btnActionPerformed
        new CadastroProcesso(this.advogado).setVisible(true);
        dispose();
    }//GEN-LAST:event_adcionar_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adcionar_btn;
    private javax.swing.JTextField codigo_txt;
    private javax.swing.JButton editar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton manter_btn;
    private javax.swing.JTextField nome_txt;
    private javax.swing.JButton salvar_btn;
    // End of variables declaration//GEN-END:variables
}
